### ISSUE TITLE
Investigate Travis build times ( averaging > 13 minutes up from 6 minutes)

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#367]
![Screen Shot 2019-10-07 at 10 59 50 AM](https://user-images.githubusercontent.com/29607818/66336307-aedd1e80-e8f1-11e9-999a-fe4fe69af786.png)

Lately builds have been taking 3x as long to finish. I believe this has to do with the most recent changes to the visual regression testing suite (https://github.com/SAP/fundamental-styles/pull/313), but we should investigate and improve on this time.

**Comment by OlegsPesudovs** [comment]
Greetings @droshev ,
Looked a bit into performance and here is what it came down to:

BackstopJS is executing bitmap compare, X-number compares in parallel at a time. It seems that the process is not very light-weight and thus dependent on hardware. The amount of compares it does in parallel can be adjusted via "asyncCompareLimit" parameter in your generated backstopConfig.js. "asyncCaptureLimit" parameter can also slightly affect performance, but I did not see any noticeable difference while tweaking it and the number cannot be too high for that one. Due to heavy-weight nature of tests and dependence on hardware, "asyncCompareLimit" should be adjusted in small increments.

Default value for "asyncCompareLimit" is 20 if I am not mistaken, and resulted in 1006 tests taking ~820 seconds for me. With "asyncCompareLimit" 150, it dropped slightly down to ~740 seconds. At 200 it actually froze a couple of times and took considerably longer (over 1100s).
Some users reported that using Puppeteer engine helped cut down the time a bit more, and using "mergeImgHack": true parameter even more (this way it should compare a 'page' of results at a time, instead of single image), but there are some slight differences in engines and the results were a bit different from expected (for ex. having image be 1px lower), which resulted in almost all tests failing. And the resulting time didn't change much or worsened.

It should be possible however to make it better by splitting tests into separate parts and running them in parallel while in Travis build (doc.: https://docs.travis-ci.com/user/speeding-up-the-build/). Of course I cannot test this, but I assume the code for travis.yml would look smth like this, after splitting the tests and generating the configs:

```
include:
  - stage: Lint and prepare test
    script: npm run lint && npm run test:ci-config
  - stage: Test
    env:
      - TEST_CONFIG=config1
      - TEST_CONFIG=config2
      - TEST_CONFIG=config3
    script: npm run test:linux-fix && server-test start:playground http-get://localhost:3030 test:visual:$TEST_CONFIG
	stage: Pre-release
	...
```
Please let me know what you think.
